#!ruby
name 'puppetlabs-mcollective'
version '1.1.3'
source 'git://github.com/puppetlabs/puppetlabs-mcollective.git'
author 'Puppet Labs'
license 'Apache Version 2.0'
summary 'MCollective Puppet Module'
description 'Module to install and configure mcollective.'
project_page 'https://github.com/puppetlabs/puppetlabs-mcollective'
dependency 'richardc/datacat', '0.4.x'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
