#!ruby
name 'puppetlabs-mcollective'
version '1.1.2'
description 'Module to install and configure mcollective.'
project_page 'https://github.com/puppetlabs/puppetlabs-mcollective'
dependency 'puppetlabs/activemq', '0.2.x'
dependency 'richardc/datacat', '0.4.x'
dependency 'garethr/erlang'
dependency 'puppetlabs/rabbitmq'
dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/java_ks'
